name: Create Linear Issue from PR

on:
  pull_request:
    types: [opened]

jobs:
  create-linear-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linear Issue
        uses: linearapp/linear-action@v1
        with:
          linear-api-key: ${{ secrets.LINEAR_API_KEY }}
          team: ${{ secrets.LINEAR_TEAM_KEY }} # Just the team KEY, not full ID (like "ENG" or "PROD")
          title: "[PR] ${{ github.event.pull_request.title }}"
          description: |
            PR: #${{ github.event.pull_request.number }} ${{ github.event.pull_request.html_url }}
            Author: ${{ github.event.pull_request.user.login }}
            
            ${{ github.event.pull_request.body }}
